language: rust
cache: cargo
sudo: required
rust:
   - stable
   - beta
   - nightly
matrix:
    allow_failures:
        - rust:
            - beta
            - nightly
install:
   - sudo add-apt-repository ppa:team-xbmc/ppa -y
   - sudo apt-get update -q
   - sudo apt-get install libsdl2-dev
before_script:
   - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
   - ./all-crates-do test-travis
env:
   global:
      - TRAVIS_CARGO_NIGHTLY_FEATURE=""
      - LD_LIBRARY_PATH: "/usr/local/lib"
