[package]
name = "open_aoe_media"
description = """
    OpenAOE media (rendering + audio) crate
"""
license = "MIT"
version = "0.1.0"
keywords = ["aoe", "age", "empires", "genie", "engine"]
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]
workspace = "../../"

[dependencies]
error-chain = "0.5"
nalgebra = "0.10"

# TODO: Move sdl2 back into the dependencies ASAP (hopefully 0.3)
[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"
rev = "1f1d8fadc7a915eb9a72a4090ac6b0a3fe5376da"

[dependencies.open_aoe_types]
path = "../types"
