[package]
name = "open_aoe_media"
description = """
    OpenAOE media (rendering + audio) crate
"""
license = "MIT"
version = "0.1.0"
keywords = ["aoe", "age", "empires", "genie", "engine"]
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]
workspace = "../../"

[dependencies]
error-chain = "0.5"
sdl2 = "0.25"
nalgebra = "0.10"

[dependencies.open_aoe_types]
path = "../types"
