[package]
name = "drs_extractor"
version = "0.1.0"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]

[dependencies]
clap = "2.17"
chariot_drs = "0.1"
chariot_palette = "0.1"

[dependencies.chariot_slp]
path = "../../crates/file_formats/slp"
