[package]
name = "slp_viewer"
version = "0.1.0"
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]

[dependencies]
clap = "2.17"
minifb = "0.9"
chariot_drs = "0.1"
chariot_slp = "0.1"
chariot_palette = "0.1"