[package]
name = "drs_browser"
version = "0.1.0"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
workspace = "../../"

[dependencies]
clap = "2.17.1"
pancurses = "^0.8"

[dependencies.open_aoe_drs]
path = "../../crates/file_formats/drs"