[package]
name = "open_aoe_resource"
description = """
    OpenAOE resource management crate
"""
license = "MIT"
version = "0.1.0"
keywords = ["aoe", "age", "empires", "genie", "engine"]
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]

[dependencies]
error-chain = "0.2"

[dependencies.open_aoe_drs]
path = "../file_formats/drs"
[dependencies.open_aoe_slp]
path = "../file_formats/slp"
[dependencies.open_aoe_palette]
path = "../file_formats/palette"
[dependencies.open_aoe_media]
path = "../media"
[dependencies.open_aoe_types]
path = "../types"
[dependencies.open_aoe_identifier]
path = "../identifier"
