[package]
name = "open_aoe_identifier"
description = """
    Identifier types for OpenAOE
"""
license = "MIT"
version = "0.1.0"
authors = ["Kevin Fuller <angered.ghandi@gmail.com>"]
workspace = "../../"
